<?xml version="1.0" encoding="utf-8"?>
<TestRun id="a800565b-dc4f-426b-ad60-a862d833dd2e" name="@sagesoho01 2025-08-30 19:35:24" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2025-08-30T19:35:24.3072953+09:00" queuing="2025-08-30T19:35:24.3072954+09:00" start="2025-08-30T19:33:19.8832864+09:00" finish="2025-08-30T19:35:24.3174908+09:00" />
  <TestSettings name="default" id="7ae62518-25b6-4826-b59f-12ff4d1a5416">
    <Deployment runDeploymentRoot="_sagesoho01_2025-08-30_19_35_24" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="315970dc-e669-4ec1-8f07-54717221d90b" testId="e6ab55d5-38d6-0580-e5b0-7764a0bff5a2" testName="Kafka.Ksql.Linq.Tests.Integration.KafkaConnectivityTests.ProducerConsumer_RoundTrip" computerName="sagesoho01" duration="00:02:15.1419321" startTime="2025-08-30T19:35:24.2048388+09:00" endTime="2025-08-30T19:35:24.2048582+09:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="315970dc-e669-4ec1-8f07-54717221d90b">
      <Output>
        <ErrorInfo>
          <Message>System.TimeoutException : Kafka not reachable at localhost:9092</Message>
          <StackTrace>   at PhysicalTestEnv.Health.WaitForKafkaAsync(String bootstrapServers, Nullable`1 timeout) in /mnt/c/dev/rc02/physicalTests/Env/Health.cs:line 25
   at Kafka.Ksql.Linq.Tests.Integration.EnvKafkaConnectivityTests.SetupAsync() in /mnt/c/dev/rc02/physicalTests/Connectivity/KafkaConnectivityTests.cs:line 111
   at Kafka.Ksql.Linq.Tests.Integration.KafkaConnectivityTests.ProducerConsumer_RoundTrip() in /mnt/c/dev/rc02/physicalTests/Connectivity/KafkaConnectivityTests.cs:line 18
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Kafka.Ksql.Linq.Tests.Integration.KafkaConnectivityTests.ProducerConsumer_RoundTrip" storage="/mnt/c/dev/rc02/physicaltests/bin/release/net8.0/kafka.ksql.linq.tests.integration.dll" id="e6ab55d5-38d6-0580-e5b0-7764a0bff5a2">
      <Execution id="315970dc-e669-4ec1-8f07-54717221d90b" />
      <TestMethod codeBase="/mnt/c/dev/rc02/physicalTests/bin/Release/net8.0/Kafka.Ksql.Linq.Tests.Integration.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Kafka.Ksql.Linq.Tests.Integration.KafkaConnectivityTests" name="ProducerConsumer_RoundTrip" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="e6ab55d5-38d6-0580-e5b0-7764a0bff5a2" executionId="315970dc-e669-4ec1-8f07-54717221d90b" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.6+bf9b858c26 (64-bit .NET 8.0.19)
[xUnit.net 00:00:00.22]   Discovering: Kafka.Ksql.Linq.Tests.Integration
[xUnit.net 00:00:00.29]   Discovered:  Kafka.Ksql.Linq.Tests.Integration
[xUnit.net 00:00:00.29]   Starting:    Kafka.Ksql.Linq.Tests.Integration
[xUnit.net 00:02:15.49]       System.TimeoutException : Kafka not reachable at localhost:9092
[xUnit.net 00:02:15.49]       Stack Trace:
[xUnit.net 00:02:15.49]         /mnt/c/dev/rc02/physicalTests/Env/Health.cs(25,0): at PhysicalTestEnv.Health.WaitForKafkaAsync(String bootstrapServers, Nullable`1 timeout)
[xUnit.net 00:02:15.49]         /mnt/c/dev/rc02/physicalTests/Connectivity/KafkaConnectivityTests.cs(111,0): at Kafka.Ksql.Linq.Tests.Integration.EnvKafkaConnectivityTests.SetupAsync()
[xUnit.net 00:02:15.49]         /mnt/c/dev/rc02/physicalTests/Connectivity/KafkaConnectivityTests.cs(18,0): at Kafka.Ksql.Linq.Tests.Integration.KafkaConnectivityTests.ProducerConsumer_RoundTrip()
[xUnit.net 00:02:15.49]         --- End of stack trace from previous location ---
[xUnit.net 00:02:15.50]   Finished:    Kafka.Ksql.Linq.Tests.Integration
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="sagesoho01" outcome="Error" timestamp="2025-08-30T19:35:24.2023642+09:00">
        <Text>[xUnit.net 00:02:15.49]     Kafka.Ksql.Linq.Tests.Integration.KafkaConnectivityTests.ProducerConsumer_RoundTrip [FAIL]</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>